### ISSUE TITLE
Training code for "landmark_detection_56_se_external.onnx"

### ISSUE THREAD

**Issue by sainisanjay** [cunjian/pytorch_face_landmark#34]
Could you please let us know whether somewhere training code is available for the model "landmark_detection_56_se_external.onnx".

**Comment by sainisanjay** [comment]
Hi @cunjian,
I tried to train the model with WFLW dataset but when i start the training i got below error.

```
python train.py 
[2022-07-08 23:33:35,668] [p32093] [train.py:31] [INFO] workers: 0
[2022-07-08 23:33:35,668] [p32093] [train.py:31] [INFO] devices_id: 0
[2022-07-08 23:33:35,668] [p32093] [train.py:31] [INFO] test_initial: False
[2022-07-08 23:33:35,668] [p32093] [train.py:31] [INFO] base_lr: 0.0001
[2022-07-08 23:33:35,669] [p32093] [train.py:31] [INFO] weight_decay: 1e-06
[2022-07-08 23:33:35,669] [p32093] [train.py:31] [INFO] lr_patience: 40
[2022-07-08 23:33:35,669] [p32093] [train.py:31] [INFO] start_epoch: 1
[2022-07-08 23:33:35,669] [p32093] [train.py:31] [INFO] end_epoch: 500
[2022-07-08 23:33:35,669] [p32093] [train.py:31] [INFO] snapshot: ./checkpoint/snapshot/
[2022-07-08 23:33:35,669] [p32093] [train.py:31] [INFO] log_file: ./checkpoint/train.logs
[2022-07-08 23:33:35,669] [p32093] [train.py:31] [INFO] tensorboard: ./checkpoint/tensorboard
[2022-07-08 23:33:35,669] [p32093] [train.py:31] [INFO] resume: 
[2022-07-08 23:33:35,669] [p32093] [train.py:31] [INFO] dataroot: ./data/train_data/list.txt
[2022-07-08 23:33:35,669] [p32093] [train.py:31] [INFO] val_dataroot: ./data/test_data/list.txt
[2022-07-08 23:33:35,669] [p32093] [train.py:31] [INFO] train_batchsize: 256
[2022-07-08 23:33:35,669] [p32093] [train.py:31] [INFO] val_batchsize: 256
Traceback (most recent call last):
  File "train.py", line 214, in <module>
    main(args)
  File "train.py", line 140, in main
    criterion, optimizer, epoch)
  File "train.py", line 64, in train
    args.train_batchsize)
  File "/home/adas/anaconda3/envs/cv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/adas/workspace/faceLandmarkDetectionCPU/pytorch_face_landmark/pfld/loss.py", line 13, in forward
    weight_angle = torch.sum(1 - torch.cos(angle - euler_angle_gt), axis=1)
RuntimeError: The size of tensor a (28) must match the size of tensor b (3) at non-singleton dimension 3
```
Could you please indicate or help me whats going wrong in my training.
